### ISSUE TITLE
Run Java iOS test sample and got error from console, but TestDroid email noticed Finished

### ISSUE THREAD

**Issue by ansonliao** [bitbar/test-samples#65] opened 2015-11-20 08:07 UTC
Dear Sir,
I clone the sample project and run Java iOS test sample in command line, and maven console came that ERROR, but TestDriod sent out a email that the test finished.

Could you provide the what is problem in error?

command run:

```
mvn clean test -Dtest=com.testdroid.appium.ios.sample.SampleAppiumiOSTest
```

and got the error message:

```
Running com.testdroid.appium.ios.sample.SampleAppiumiOSTest
response:{"status":0,"sessionId":"9b3c88ec-0c1a-436e-8c8a-45742cf57065","value":{"message":"uploads successful","uploadCount":1,"rejectCount":0,"expiresIn":1800,"uploads":{"file":"9b3c88ec-0c1a-436e-8c8a-45742cf57065/BitbarIOSSample.ipa"},"rejects":{}}}
File id:4d6bb297-00ac-4fba-9a4c-bb9afa6fc920/BitbarIOSSample.ipa
Capabilities:Capabilities [{testdroid_password=xxxx, testdroid_description=Appium project description, app=com.bitbar.testdroid.BitbarIOSSample, testdroid_app=4d6bb297-00ac-4fba-9a4c-bb9afa6fc920/BitbarIOSSample.ipa, testdroid_target=iOS, testdroid_project=SHOPPO iOS, testdroid_username=xxxx@xxxx.com, testdroid_device=iPad 3 A1416 8.2, platformName=iOS, device=iphone, deviceName=iOS Phone, testdroid_testrun=iOS Run}]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 11.97 sec <<< FAILURE!

Results :

Tests in error: 
  com.testdroid.appium.ios.sample.SampleAppiumiOSTest: com.testdroid.api.APIException: 400 Bad Request

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

```

**Comment by marverix** [comment] 2020-05-01 07:06
The issue is probably deprecated. Closing for now. Please feel free to re-open it, if you feel that it's still valid.

**Closed by marverix** 2020-05-01 07:06 UTC
